name: Deploy
concurrency:
  group: "pr-${{ github.event.pull_request.number }}"
  cancel-in-progress: true
on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        # with:
          # persist-credentials: false
      # - uses: webfactory/ssh-agent@v0.5.3
      #   with:
      #       ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Set node version
        uses: actions/setup-node@v2
        with:
          node-version-file: .nvmrc
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install node modules
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGES_READ_TOKEN }}
        run: |
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> .npmrc
          git config --global url."https://${GITHUB_TOKEN}@github.com".insteadOf ssh://git@github.com
          npm ci --verbose
      - name: Cache multiple paths
        uses: actions/cache@v3
        with:
          path: |
            /tmp/webpack-cache
            /tmp/babel-cache
          key: ${{ runner.os }}-client-${{ github.ref_name }}-${{ hashFiles('client/webpack.prod.js') }}
      - name: compile
        run: |
          rm dist/*.js.map
          rm dist/*.js
          npm pack

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
            name: package
            path: "*.tgz"


  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Upload
        uses: actions/download-artifact@v2
        with:
            name: package
      - uses: actions/setup-node@v2
        with:
          node-version: 12.22.0
          registry-url: https://npm.pkg.github.com/
          scope: "@landtechnologies"
      - run: echo "registry=https://npm.pkg.github.com/@landtechnologies" >> .npmrc
      - run: npm publish $(ls *.tgz)
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
